language: ruby
script: git submodule init; git submodule update; bundle exec rake test
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
